package com.drivesafe.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.*;

// ─────────────────────────────────────────────────────────────────────────────
// TripUploadResponse — returned by POST /api/trips/upload
//
// This is the richest response in the app — it carries the full result of
// the ML pipeline: DriveScore, risk classification, all telemetry stats,
// the OpenAI recommendation, the Folium map URL, and points earned.
//
// React TripHistory.jsx uses this immediately after upload to:
//   1. Show the new trip card with score + stats
//   2. Display the AI recommendation in the "View AI Analysis" modal
//   3. Render the map via the mapUrl iframe
//   4. Update the navbar points pill
//
// JSON shape:
// {
//   "tripId":           42,
//   "driveScore":       57.75,
//   "riskLevel":        "Moderate",
//   "maxSpeed":         109.0,
//   "avgSpeed":         72.4,
//   "distanceKm":       23.0,
//   "hardBrakingCount": 3,
//   "sharpTurnCount":   2,
//   "weatherCondition": "Clear Weather",
//   "isDaytime":        true,
//   "aiRecommendation": "Your max speed of 109 km/h...",
//   "mapUrl":           "http://localhost:5000/view-map/42",
//   "pointsEarned":     25,
//   "message":          "Trip processed successfully"
// }
// ─────────────────────────────────────────────────────────────────────────────
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TripUploadResponse {

    // ── Identity ──────────────────────────────────────────────────────
    // DB primary key — used by frontend to fetch map and AI analysis later
    private Long tripId;

    // ── ML Score ──────────────────────────────────────────────────────
    // 0–100, higher = riskier. Returned by Flask LightGBM /predict
    private double driveScore;

    // "Safe" | "Moderate" | "High" — derived from driveScore in TripService
    private String riskLevel;

    // ── Telemetry stats ───────────────────────────────────────────────
    // Aggregated from all CSV rows in TripService.extractStats()

    private double maxSpeed;           // km/h — peak reading
    private double avgSpeed;           // km/h — mean across trip
    private double distanceKm;         // Haversine sum across GPS points
    private double maxAcceleration;    // m/s² — absolute max

    private int hardBrakingCount;      // deceleration < -2.94 m/s²
    private int sharpTurnCount;        // |accel| > 1.5 at speed > 20 km/h

    // ── Conditions ────────────────────────────────────────────────────
    // From OpenWeatherMap at trip start coordinates
    private String  weatherCondition;  // "Clear Weather", "Rainy", "Foggy" etc.
    private boolean isDaytime;         // true = day, false = night

    // ── AI output ─────────────────────────────────────────────────────
    // Generated by AIRecommendationService (GPT-4o-mini)
    // Null if OpenAI was unreachable — frontend should handle gracefully
    private String aiRecommendation;

    // ── Map ───────────────────────────────────────────────────────────
    // URL of Folium HTML map — null if Flask map generation failed
    private String mapUrl;

    private String heatmapUrl;   // ← ADD THIS
    // ── Gamification ──────────────────────────────────────────────────
    // Points awarded this trip (10 / 25 / 50 based on risk level)
    // Frontend uses this to animate the navbar points pill increment
    private int pointsEarned;

    // ── Status ────────────────────────────────────────────────────────
    private String message;
}