package com.drivesafe.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Entity
@Table(
        name = "trips",
        indexes = {
                // Fast lookup of all trips for a user, newest first (used constantly)
                @Index(name = "idx_trips_user_id_created_at", columnList = "user_id, created_at DESC"),
                // Used by DriscScoringService to fetch top-N trips
                @Index(name = "idx_trips_user_id",            columnList = "user_id")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = {"user"}) // avoid circular reference in logs
public class Trip {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ── Relationship ──────────────────────────────────────────────────
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_trips_user_id"))
    private User user;

    // ── ML Score ──────────────────────────────────────────────────────
    // DriveScore: 0–100, higher = riskier
    // Returned by Flask LightGBM model (POST /predict)
    @Column(name = "drive_score", nullable = false)
    private double driveScore;

    // ── Speed Telemetry ───────────────────────────────────────────────
    // All values sourced from OBD CSV rows after aggregation in TripService

    @Column(name = "max_speed")
    private double maxSpeed;           // km/h — max single reading in the trip

    @Column(name = "avg_speed")
    private double avgSpeed;           // km/h — mean across all rows

    // ── Distance ─────────────────────────────────────────────────────
    // Computed via Haversine summation across GPS points in TripService
    @Column(name = "distance")
    private double distance;           // km

    // ── Acceleration ─────────────────────────────────────────────────
    @Column(name = "max_acceleration")
    private double maxAcceleration;    // m/s² — absolute value max

    // ── Safety Events ─────────────────────────────────────────────────
    // Counted in TripService.extractStats() from raw CSV rows

    @Column(name = "hard_braking_count")
    private int hardBrakingCount;      // deceleration < -2.94 m/s²

    @Column(name = "sharp_turn_count")
    private int sharpTurnCount;        // |accel| > 1.5 m/s² at speed > 20 km/h

    // ── Conditions ────────────────────────────────────────────────────
    // From OpenWeatherMap at trip start coordinates

    @Column(name = "weather_condition", length = 50)
    private String weatherCondition;   // "Clear Weather", "Rainy", "Foggy" etc.

    @Column(name = "is_daytime", nullable = false)
    @Builder.Default
    private boolean daytime = true;    // true = day, false = night (from OWM sunrise/sunset)

    // ── AI Output ─────────────────────────────────────────────────────
    // Generated by AIRecommendationService (GPT-4o-mini), stored after trip save
    @Column(name = "ai_recommendation", columnDefinition = "TEXT")
    private String aiRecommendation;

    // ── Map ───────────────────────────────────────────────────────────
    // URL of Folium-generated HTML route map (served by Flask)
    @Column(name = "map_url", length = 500)
    private String mapUrl;

    // ── Timestamps ────────────────────────────────────────────────────
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "heatmap_url", length = 500)
    private String heatmapUrl;

    // ── Lifecycle ─────────────────────────────────────────────────────
    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }

    // ── Convenience ───────────────────────────────────────────────────
    /**
     * Returns the risk label for this trip's DriveScore.
     * Mirrors TripService.getRiskLevel() — kept here for convenience
     * so entities can be used in templates without injecting the service.
     *   Safe     : score ≤ 40
     *   Moderate : score ≤ 65
     *   High     : score > 65
     */
    @Transient
    public String getRiskLevel() {
        if (driveScore <= 40) return "Safe";
        if (driveScore <= 65) return "Moderate";
        return "High";
    }
}